name: book_analysis

services:
  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    # command: mongod --port ${MONGO_PORT:-27017}
    ports:
      - "${DATABASE_PORT:-27017}:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - TZ=Europe/Madrid
    volumes:
      - mongo_data:/data/db
      - './init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh'
    restart: unless-stopped

  # alexa-skill-api:
  #   container_name: alexa-skill-api
  #   build:
  #     context: .
  #   ports:
  #     - "${API_PORT:-3000}:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - mongodb
  #     - ollama
  #   restart: unless-stopped

volumes:
  mongo_data: